"""Field lists aligned with schema/src/*.json (name + type only)."""
from __future__ import annotations

SRC_PERSON_FIELDS: list[dict[str, str]] = [
    {"name": 'identity_type', "type": 'int'},
    {"name": 'operator_Id', "type": 'long'},
    {"name": 'network_pager_id', "type": 'string'},
    {"name": 'isdn_world_pstn', "type": 'long'},
    {"name": 'additional_isdn_pstn', "type": 'long'},
    {"name": 'isdn', "type": 'long'},
    {"name": 'imsi', "type": 'long'},
    {"name": 'imei', "type": 'long'},
    {"name": 'iccid', "type": 'string'},
    {"name": 'isdn_cdma', "type": 'long'},
    {"name": 'cdma_imsi_a', "type": 'long'},
    {"name": 'cdma_Imei_a', "type": 'long'},
    {"name": 'cdma_imsi_b', "type": 'long'},
    {"name": 'icc_cdma', "type": 'long'},
    {"name": 'hardware_type', "type": 'int'},
    {"name": 'mac', "type": 'string'},
    {"name": 'atm_vpi_network', "type": 'string'},
    {"name": 'atm_vci_network', "type": 'string'},
    {"name": 'login', "type": 'string'},
    {"name": 'ip_type', "type": 'int'},
    {"name": 'ip4', "type": 'string'},
    {"name": 'ip6', "type": 'string'},
    {"name": 'email', "type": 'string'},
    {"name": 'pin', "type": 'string'},
    {"name": 'isdn_date_network', "type": 'long'},
    {"name": 'user_domain', "type": 'string'},
    {"name": 'reserved', "type": 'string'},
    {"name": 'ip_mask_type', "type": 'int'},
    {"name": 'ip4_mask', "type": 'string'},
    {"name": 'ip6_mask', "type": 'string'},
    {"name": 'ip_type_voip', "type": 'int'},
    {"name": 'ip4_voip', "type": 'string'},
    {"name": 'ip6_voip', "type": 'string'},
    {"name": 'voip_starter_name', "type": 'string'},
    {"name": 'voip_calling_isdn', "type": 'long'},
    {"name": 'contract_date', "type": 'date'},
    {"name": 'contract_number', "type": 'string'},
    {"name": 'actually_from', "type": 'timestamp'},
    {"name": 'actually_to', "type": 'timestamp'},
    {"name": 'client_type', "type": 'int'},
    {"name": 'struct_fio_type', "type": 'int'},
    {"name": 'first_name', "type": 'string'},
    {"name": 'second_name', "type": 'string'},
    {"name": 'last_name', "type": 'string'},
    {"name": 'abonent', "type": 'string'},
    {"name": 'birth_day', "type": 'date'},
    {"name": 'struct_dul_type', "type": 'int'},
    {"name": 'dul_serial', "type": 'string'},
    {"name": 'doc_number', "type": 'string'},
    {"name": 'document', "type": 'string'},
    {"name": 'dul_department', "type": 'string'},
    {"name": 'unstruct_dul', "type": 'string'},
    {"name": 'doc_type', "type": 'int'},
    {"name": 'client_bank', "type": 'string'},
    {"name": 'client_bank_account', "type": 'string'},
    {"name": 'org_name', "type": 'string'},
    {"name": 'inn', "type": 'long'},
    {"name": 'contact', "type": 'string'},
    {"name": 'contact_info', "type": 'string'},
    {"name": 'inner_users_list', "type": 'string'},
    {"name": 'org_bank', "type": 'string'},
    {"name": 'org_bank_account', "type": 'string'},
    {"name": 'abonent_status', "type": 'int'},
    {"name": 'main_service_start_ts', "type": 'timestamp'},
    {"name": 'main_service_end_ts', "type": 'timestamp'},
    {"name": 'abonent_last_location', "type": 'int'},
    {"name": 'lac', "type": 'long'},
    {"name": 'cell', "type": 'long'},
    {"name": 'timing_advance', "type": 'string'},
    {"name": 'network_location_id', "type": 'string'},
    {"name": 'network_mac', "type": 'string'},
    {"name": 'latitude', "type": 'double'},
    {"name": 'longitude', "type": 'double'},
    {"name": 'coordinates', "type": 'string'},
    {"name": 'geo_json', "type": 'string'},
    {"name": 'geo_projection_type', "type": 'int'},
    {"name": 'ip_location_type', "type": 'string'},
    {"name": 'ip4_location', "type": 'string'},
    {"name": 'ip6_location', "type": 'string'},
    {"name": 'ip_port_location', "type": 'string'},
    {"name": 'object_conn_desc', "type": 'string'},
    {"name": 'cross_desc', "type": 'string'},
    {"name": 'block_desc', "type": 'string'},
    {"name": 'pair_desc', "type": 'string'},
    {"name": 'reserve', "type": 'string'},
    {"name": 'network_conn_type', "type": 'int'},
    {"name": 'address_registration', "type": 'string'},
    {"name": 'abonent_postal_address', "type": 'string'},
    {"name": 'address_invoice', "type": 'string'},
    {"name": 'address_installation', "type": 'string'},
    {"name": 'abonent_reserved_address', "type": 'string'},
    {"name": 'service_list', "type": 'string'},
    {"name": 'COL84', "type": 'string'},
    {"name": 'COL85', "type": 'string'},
    {"name": 'COL86', "type": 'string'},
    {"name": 'last_change_date', "type": 'date'},
    {"name": 'end_contract_date', "type": 'date'},
    {"name": 'tariff', "type": 'string'},
    {"name": 'dealer', "type": 'string'},
]

SRC_IMSI_FIELDS: list[dict[str, str]] = [
    {"name": 'value', "type": 'string'},
]

SRC_IMEI_FIELDS: list[dict[str, str]] = [
    {"name": 'value', "type": 'string'},
]

SRC_MSISDN_FIELDS: list[dict[str, str]] = [
    {"name": 'value', "type": 'string'},
]

SRC_CDR_FIELDS: list[dict[str, str]] = [
    {"name": 'Started', "type": 'string'},
    {"name": 'Duration', "type": 'uint32'},
    {"name": 'Category', "type": 'uint8'},
    {"name": 'Event', "type": 'uint32'},
    {"name": 'Service', "type": 'uint32'},
    {"name": 'CallingNumber', "type": 'string'},
    {"name": 'CallingSource', "type": 'string'},
    {"name": 'CallingRegion', "type": 'string'},
    {"name": 'CalledNumber', "type": 'string'},
    {"name": 'CalledSource', "type": 'string'},
    {"name": 'CalledRegion', "type": 'string'},
    {"name": 'DialedNumber', "type": 'string'},
    {"name": 'Owner', "type": 'int'},
    {"name": 'IMSI', "type": 'string'},
    {"name": 'IMEI', "type": 'string'},
    {"name": 'BSStartLac', "type": 'uint16'},
    {"name": 'BSStartCell', "type": 'uint32'},
    {"name": 'BSEndLac', "type": 'uint16'},
    {"name": 'BSEndCell', "type": 'uint32'},
    {"name": 'RouteIn', "type": 'string'},
    {"name": 'RouteOut', "type": 'string'},
    {"name": 'RecEntNumber', "type": 'string'},
    {"name": 'OwnerMCCMNC', "type": 'string'},
    {"name": 'RecipientMCCMNC', "type": 'string'},
    {"name": 'RecEntOwnerRegion', "type": 'string'},
    {"name": 'dateTimeOriginal', "type": 'string'},
    {"name": 'Custom', "type": 'string'},
    {"name": 'RecEntType', "type": 'string'},
    {"name": 'PartyEntType', "type": 'string'},
    {"name": 'SequenceID', "type": 'string'},
    {"name": 'CauseDiagnostic', "type": 'string'},
    {"name": 'OwnerMSRNNumber', "type": 'string'},
    {"name": 'OtherMSRNNumber', "type": 'string'},
    {"name": 'Intermediate', "type": 'string'},
]

SRC_SMS_FIELDS: list[dict[str, str]] = [
    {"name": 'Started', "type": 'string'},
    {"name": 'Event', "type": 'int'},
    {"name": 'Calling', "type": 'string'},
    {"name": 'Called', "type": 'string'},
    {"name": 'Owner', "type": 'int'},
    {"name": 'SMSC', "type": 'long'},
    {"name": 'IMSI', "type": 'string'},
    {"name": 'IMEI', "type": 'string'},
    {"name": 'MCC', "type": 'int'},
    {"name": 'MNC', "type": 'int'},
    {"name": 'Lac', "type": 'int'},
    {"name": 'Cell', "type": 'int'},
    {"name": 'MAC', "type": 'string'},
    {"name": 'BSID', "type": 'int'},
    {"name": 'Latitude', "type": 'double'},
    {"name": 'Longitude', "type": 'double'},
    {"name": 'PDPAddress.IPV4', "type": 'string'},
    {"name": 'PDPAddress.IPV6', "type": 'string'},
    {"name": 'PDPAddress.Port', "type": 'string'},
    {"name": 'Message', "type": 'string'},
    {"name": 'Custom', "type": 'string'},
]

SRC_GPRS_FIELDS: list[dict[str, str]] = [
    {"name": 'Started', "type": 'string'},
    {"name": 'Duration', "type": 'uint32'},
    {"name": 'Category', "type": 'uint8'},
    {"name": 'Upload', "type": 'string'},
    {"name": 'Download', "type": 'string'},
    {"name": 'Event', "type": 'uint32'},
    {"name": 'Service', "type": 'uint32'},
    {"name": 'CauseDiagnostic', "type": 'string'},
    {"name": 'CallingNumber', "type": 'string'},
    {"name": 'CallingSource', "type": 'string'},
    {"name": 'CallingRegion', "type": 'string'},
    {"name": 'CalledNumber', "type": 'string'},
    {"name": 'CalledSource', "type": 'string'},
    {"name": 'CalledRegion', "type": 'string'},
    {"name": 'DialedNumber', "type": 'string'},
    {"name": 'Owner', "type": 'int'},
    {"name": 'PDPV4Address', "type": 'string'},
    {"name": 'PDPV6Address', "type": 'string'},
    {"name": 'IMSI', "type": 'string'},
    {"name": 'IMEI', "type": 'string'},
    {"name": 'APN', "type": 'string'},
    {"name": 'BSStartLac', "type": 'uint16'},
    {"name": 'BSStartCell', "type": 'uint32'},
    {"name": 'BSEndLac', "type": 'uint16'},
    {"name": 'BSEndCell', "type": 'uint32'},
    {"name": 'RouteIn', "type": 'string'},
    {"name": 'RouteOut', "type": 'string'},
    {"name": 'RecEntType', "type": 'string'},
    {"name": 'RecEntNumber', "type": 'string'},
    {"name": 'PartyEntType', "type": 'string'},
    {"name": 'PartyEntNumber', "type": 'string'},
    {"name": 'OwnerMCCMNC', "type": 'string'},
    {"name": 'RecipientMCCMNC', "type": 'string'},
    {"name": 'PartyMCCMNC', "type": 'string'},
    {"name": 'RecEntOwnerRegion', "type": 'string'},
    {"name": 'dateTimeOriginal', "type": 'string'},
    {"name": 'Custom', "type": 'string'},
    {"name": 'RAT', "type": 'string'},
    {"name": 'LT', "type": 'string'},
]

SRC_LOCATION_FIELDS: list[dict[str, str]] = [
    {"name": 'Started', "type": 'string'},
    {"name": 'Event', "type": 'int'},
    {"name": 'Served', "type": 'string'},
    {"name": 'IMSI', "type": 'string'},
    {"name": 'IMEI', "type": 'string'},
    {"name": 'MCC', "type": 'string'},
    {"name": 'MNC', "type": 'string'},
    {"name": 'Lac', "type": 'int'},
    {"name": 'Cell', "type": 'int'},
    {"name": 'MAC', "type": 'int'},
    {"name": 'BSID', "type": 'int'},
    {"name": 'Latitude', "type": 'double'},
    {"name": 'Longitude', "type": 'double'},
    {"name": 'IP4Address', "type": 'string'},
    {"name": 'IP6Address', "type": 'string'},
    {"name": 'Port', "type": 'int'},
    {"name": 'TA', "type": 'int'},
    {"name": 'Source', "type": 'int'},
    {"name": 'Custom', "type": 'string'},
]
